### ISSUE TITLE
Data Munging

### ISSUE THREAD

**Issue by hmlanden** [hmlanden/climatology#1]
Select and clean datasets. Since we're using Tableau, needs to be in any one of these formats:

- Excel
- Text file
- JSON file
- PDF 
- Spatial file
- Statistical file

**Comment by hmlanden** [comment]
Note: Whenever you figure out which data we're using, make sure to make a note of it! We'll want to record and reference where we sourced it from, don't want to forget.

**Comment by cpontier** [comment]
Absolutely. Please verify that you got this response.
